### ISSUE TITLE
Nice feature, will implement it in FFmpegfs

### ISSUE THREAD

**Issue by nschlia** [andresch/trackfs#1]
This looks like a good feature, I will implement that in FFmpegfs so that the mp3's or whatever get created in the same step, see https://github.com/nschlia/ffmpegfs/issues/66

**Comment by andresch** [comment]
Cool. Looking forward to giving it a try. Let me know if I can help.

**Comment by nschlia** [comment]
Would be great if you could test the feature once it's ready. Just follow the I mentioned ticket above for progress. Should take a few days to get it ready.

The cue sheet idea is great, I could separate e.g. large concert videos into tracks, a capability I've been searching for a long time. This is the perfect solution, no need to touch the original file. Just drop a cue file in and magically, there is every song as a single file...

**Comment by nschlia** [comment]
Got a test version ready, still some work to d, though. But working and can be tested. Will push the code today.
PS:
To make further conversation easier, you could email me at nschlia@oblivion-software.de.
