### ISSUE TITLE
Make album file extension matching case-insensitive

### ISSUE THREAD

**Issue by andresch** [andresch/trackfs#13]
currently trackfs would only match ".wav" and ".flac", but not ".WAV" or ":FLAC"

**Comment by kangbeicai** [comment]
Is it possible to add a rule to match  XX.flac.cue and  XX.flac ?

**Comment by andresch** [comment]
sure; should not be too hard. Will add another ticket for that.

**Comment by andresch** [comment]
basic case-insensitive matching is provided as part of #17
