### ISSUE TITLE
Attributes of CueSheet object are included as tags in track files

### ISSUE THREAD

**Issue by kobarity** [andresch/trackfs#23]
Current trackfs shows all attributes including methods of `CueSheet` object as tags. Here are excerpts from "metaflac --list" for a track file.

```
    comment[41]: __ANNOTATIONS__={'tracks': typing.List[ForwardRef('Track')], 'albumartists': typing.List[str], 'album': <class 'str'>, 'composers': typing.List[str], 'catalog': <class 'str'>, 'discid': <class 'str'>, 'year': <class 'str'>, 'discnumber': <class 'str'>, 'totaldiscs': <class 'str'>}
    comment[42]: __CLASS__=<class 'trackfs.cuesheet.CueSheet'>
...
    comment[50]: __FORMAT__=<built-in method __format__ of CueSheet object at 0x7f9106e90580>
    comment[51]: __GE__=<method-wrapper '__ge__' of CueSheet object at 0x7f9106e90580>
```

This is caused by the following code in the `CueSheet` class.

```python
    def tags(self):
        return TagTools.object_tags(self, dir(self).remove('tracks'))
```

Please note that the list's `remove()` method always returns `None`. `TagTools.object_tags()` calls `dir(o)` when `names` argument is `None`, which results in `names` to be all attributes/methods of `CueSheet` object.

**Comment by andresch** [comment]
Thanks a lot , kobarity. 

I still recall when I wrote that line of code that I didn't recall exactly what remove() returns, but was too lazy to look it up when I saw the tags being properly displayed in my player. Next time I'll be more thorough.
