### ISSUE TITLE
No arm7 image for Raspberry Pi 4

### ISSUE THREAD

**Issue by inertia666** [andresch/trackfs#29]
I am trying to install TrackFS on my Raspberry PI 4 but it cannot find an Arm 7 image. Is there one?

**Comment by andresch** [comment]
Sorry for the late reply. 

Unfotunately I have no experience providing / publishing docker containers for other platforms than intel / adm, but I will try to learn how to do it. But this might take some time. 

Until then you might be able to help youself, if you have some knowledge with building docker See #26, where someone managed to build trackfs @kanadork manged to build a trackfs container for his arm based NAS. Maybe the same works for you too.

**Comment by inertia666** [comment]
I actually went and converted all my media from cue to tracks instead haha
